modLoader="javafml"
loaderVersion="[41,)"
license="GNU General Public License v3.0"
issueTrackerURL="https://github.com/Mr-Pineapple/AdditionalGuns/issues"

[[mods]]
    modId="additionalguns"
    version="0.6.1"
    displayName="Additional Guns"
    updateJSONURL="https://raw.githubusercontent.com/Mr-Pineapple/ModUpdateJSON/master/additionalguns/update.json"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/additional-guns"
    authors="Mr. Pineapple"
    credits="Autovw - Code, ThatAvocado_Boi, JamesTheMaker, JaMychal1, SirSpark1313, VIKTORWOOD, Mercuriousity, Stabilizer - Assets"
    description="A community addon pack for MrCrayfish's Gun Mod - To contribute, head over the GitHub or simply join discord.gg/mrcrayfish and let us know!"

[[dependencies.additionalguns]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.additionalguns]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.additionalguns]]
    modId="cgm"
    mandatory=true
    versionRange="[1.2.7,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.additionalguns]]
    modId="framework"
    mandatory=true
    versionRange="[0.3.0,)"
    ordering="NONE"
    side="BOTH"

[modproperties.additionalguns]
    catalogueItemIcon="additionalguns:ace_of_spades"
    configuredBackground="minecraft:textures/block/stripped_birch_log.png"
